### ISSUE TITLE
Get pictures and video

### ISSUE THREAD

**Issue by vtsatskin** [UWARG/computer-vision#1]
Currently we'll need images and videos to test and train our proposed algorithms. The more data the better. Captures of both target and non-target data would be good.

Where is this data currently stored? What is a good, fault tolerant location to store this data?

I'm proposing we put it in the Google Drive or whatever we currently use for sharing files.

# TODO
* [x] Get video streams from camera
* [x] Get images of target and non-target data
* [ ] Determine where to store current and future training data
